num1 = input("select number")
num2 = input("select another number")
svar = float(num1) / float(num2)
real = float(num1) ** float(num2)
print(str(real))

number1 = input("select tal")
number2 = input("select nam")
number3 = input("select tal")
number4 = input("select nam")
number5 = input("select tal")
number6 = input("select nam")
answer = float(number1) / float(number2)
answer2 = float(number3) / float(number4)
answer3 = float(number5) / float(number6)
print(answer + answer2 + answer3)

fn = input("enter fist name")
ln = input("enter last name")
s = (fn [0])
a = (fn [1])
n = (fn [2])
t = (fn [3])
h = (ln [-3])
e = (ln [-2])
d = (ln [-1])
print(s + a + n + t + h + e + d)

t1, n1 = input("täljare och nämnare mannen") split("/")
t2, n2 = input("täljare och nämnare numero do mannen ") split("/")
t3, n3 = input("täljare och nämnare number drei mannen") split("/")